Update excdata for BO QF family
lnls-sirius/control-system-constants pull request #213
Opened 2021-02-03 02:04 UTC by xresende

2021-02-03 11:53 UTC, fernandohds564 approved these changes

2021-02-03 11:54 UTC, anacso17 approved these changes

2021-02-03 12:10 UTC, murilobalves approved these changes

2021-02-05 11:12 UTC, LuanaVilela requested changes
Incorrect values for lower currents.

2021-02-08 13:17 UTC, murilobalves approved these changes

2021-02-09 03:00 UTC, LuanaVilela approved these changes

2021-02-09 11:17 UTC, fernandohds564 approved these changes

2021-02-09 13:14 UTC, LucasIB approved these changes

2021-02-09 18:31 UTC, anacso17 approved these changes

2022-12-16 16:41 UTC, xresende commented
@fernandohds564 , @anacso17 , @murilobalves,

should we drop this set of excdata atualization PRs based on re-measurements or merge them ? we should try to decide on this ando not keep it indefinitely. In my opinion we could merge.

2023-02-10 11:43 UTC, fernandohds564 commented
this one too, @xresende

2023-02-10 17:34 UTC, closed without merging